authors: Yue Pan, Zimin Chen, Xiang Li, Zhaoyang Chu, Zhiwei Fei, Han Li, He Ye
logo:
  - https://raw.githubusercontent.com/EuniAI/Prometheus/main/docs/static/images/icon.jpg
  - https://raw.githubusercontent.com/EuniAI/Prometheus/main/docs/static/images/delysium.jpg
name: Prometheus-v1.2 + GPT-5
oss: true
site: https://euni.ai/